### ISSUE TITLE
Dockerfile that can be used with AWS Lambda

### ISSUE THREAD

**Issue by sh-authorium** [yeslogic/docker-prince#6]
I'm looking to use one of the lambda base images i.e. `FROM public.ecr.aws/lambda/nodejs:20` and a modified version of Dockerfile.debian. is that something you would be able to provide?

This is what I have so far: 
```
FROM --platform=linux/amd64 public.ecr.aws/lambda/nodejs:20

ARG PRINCE_VERSION=15.3
ARG PRINCE_PACKAGE=prince-${PRINCE_VERSION}-centos7-x86_64
ARG PRINCE_PACKAGE_ARCHIVE=${PRINCE_PACKAGE}.tar.gz
ARG PRINCE_DOWNLOAD_URL=[https://www.princexml.com/download/${PRINCE_PACKAGE_ARCHIVE}](https://www.princexml.com/download/$%7BPRINCE_PACKAGE_ARCHIVE%7D)
ARG INSTALL_DIR=/usr/local

RUN dnf install -y \
  tar \
  gzip \
  which \
  findutils \
  glibc \
  libstdc++ \
  libX11-common \
  libX11 \
  libXext \
  libXrender \
  libtiff \
  libjpeg-turbo \
  libpng \
  libSM \
  giflib \
  fontconfig \
  google-noto-sans-fonts \
  khmeros-base-fonts \
  lklug-fonts \
  cjkuni-uming-fonts \
  liberation-fonts \
  ipa-gothic-fonts \
  ipa-pgothic-fonts \
  ipa-mincho-fonts \
  ipa-pmincho-fonts \
  baekmuk-ttf-fonts-common && \
  dnf clean all && \
  curl -L -o $PRINCE_PACKAGE_ARCHIVE $PRINCE_DOWNLOAD_URL && \
  tar xzf $PRINCE_PACKAGE_ARCHIVE && \
  cd $PRINCE_PACKAGE && \
  printf '%s\n' "${INSTALL_DIR}" | ./install.sh && \
  cd .. && \
  rm -rf $PRINCE_PACKAGE $PRINCE_PACKAGE_ARCHIVE && \
  ln -sf /etc/ssl/certs/ca-certificates.crt /usr/local/lib/prince/etc/curl-ca-bundle.crt
```

however I'm running into the following error when running prince.
```
bash-5.2# prince
/usr/local/lib/prince/bin/prince: error while loading shared libraries: libpng15.so.15: cannot open shared object file: No such file or directory
```

i've got libpng installed as a dep, and tried installing libpng15 with no luck
```
bash-5.2# dnf install -y libpng15
Downloading metadata...
error: No package matches 'libpng15'
```

**Comment by wezm** [comment]
>  is that something you would be able to provide?

It's not something that we have plans to provide but we do have an aws lamba version of prince. It looks like you're on the right track. `/etc/os-release` in the `public.ecr.aws/lambda/nodejs:20` image has the following:

```
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.4.20240611"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/"
SUPPORT_END="2028-03-15"
VARIANT_ID="202406131811-2023.197.0"
```

Based on that and [this note](https://docs.aws.amazon.com/linux/al2023/ug/relationship-to-fedora.html) it seems that it's based on Fedora Linux. We don't have a pre-built package for Fedora but we do have the aws-lambda build:

https://www.princexml.com/download/prince-15.3-aws-lambda.zip

If you fetch and extract that instead of the centos7 package it should work.

**Comment by sh-authorium** [comment]
I actually tried that approach as well on the same image and get another dep error 

export PRINCE_PACKAGE=prince-20240523-aws-lambda.zip
export PRINCE_PACKAGE_URL=https://www.princexml.com/download/${PRINCE_PACKAGE}

dnf install -y unzip
curl -L -o $PRINCE_PACKAGE $PRINCE_PACKAGE_URL
unzip $PRINCE_PACKAGE

and then i get a different lib error:
bash-5.2# ./prince
./prince-engine/bin/prince: error while loading shared libraries: libexpat.so.1: cannot open shared object file: No such file or directory

**Comment by wezm** [comment]
> and then i get a different lib error:

`dnf install -y expat` should fix that

**Comment by sh-authorium** [comment]
Ah good call, should have tried that but wasn't sure that was the preferred route. Here's the Dockerfile in case its helpful for anyone else looking to do this
```
FROM --platform=linux/amd64 public.ecr.aws/lambda/nodejs:20

ARG PRINCE_VERSION=15.3
ARG PRINCE_PACKAGE=prince-${PRINCE_VERSION}-aws-lambda.zip
ARG PRINCE_PACKAGE_URL=https://www.princexml.com/download/${PRINCE_PACKAGE}

RUN dnf update && dnf install -y unzip expat
RUN curl -L -o $PRINCE_PACKAGE $PRINCE_PACKAGE_URL
RUN unzip $PRINCE_PACKAGE

RUN ${LAMBDA_TASK_ROOT}/prince --version

COPY index.js ${LAMBDA_TASK_ROOT}
  
CMD [ "index.handler" ]
```
